/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type GetAllApiRawMsgGetParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
keyword?: string | null;
priority?: string | null;
start_date?: string | null;
end_date?: string | null;
has_bot_reply?: string | null;
};
