/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetAllApiRawMsgGetParams,
  SyncApiRawMsgSyncPostParams
} from '../model';

import { customAxiosInstance } from '../api.base';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * @summary Get All
 */
export const getAllApiRawMsgGet = (
    params?: GetAllApiRawMsgGetParams,
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/raw-msg/`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Sync
 */
export const syncApiRawMsgSyncPost = (
    params?: SyncApiRawMsgSyncPostParams,
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/raw-msg/sync`, method: 'POST',
        params
    },
      options);
    }
  /**
 * @summary Clear All
 */
export const clearAllApiRawMsgAllDelete = (
    
 options?: SecondParameter<typeof customAxiosInstance<unknown>>,) => {
      return customAxiosInstance<unknown>(
      {url: `/api/raw-msg/all`, method: 'DELETE'
    },
      options);
    }
  export type GetAllApiRawMsgGetResult = NonNullable<Awaited<ReturnType<typeof getAllApiRawMsgGet>>>
export type SyncApiRawMsgSyncPostResult = NonNullable<Awaited<ReturnType<typeof syncApiRawMsgSyncPost>>>
export type ClearAllApiRawMsgAllDeleteResult = NonNullable<Awaited<ReturnType<typeof clearAllApiRawMsgAllDelete>>>
